HL7/fhir-pacio-adi

FHIR-us-pacio-adi.xml, input/fsh/ADIHeaderProfile.fsh, input/fsh/Examples.fsh, input/fsh/Extensions.fsh
re-applied fix based on the master branch.
=> fix for FHIR-34819

input/pagecontent/formal_specification.md, input/pagecontent/general_guidance.md, input/pagecontent/index.md, input/pagecontent/patient_stories_and_personas.md
Added note that this IG does not cover how EHRs should be architected and is out of scope.
=> Fix for FHIR-34830 - Clarification of Use Case (Create)

input/fsh/ADIHeaderProfile.fsh, input/fsh/DocumentationObservationProfile.fsh, input/fsh/Examples.fsh, input/fsh/ExamplesBetsySmith-Johnson.fsh, input/fsh/ValueSets.fsh
* Change from LOINC#75320-2 to 42348-3
* Change Composition.category from 1..1 to 0..1 MS
* Fixed Composition.category to LOINC 42348-3
=> Fix for FHIR-34833

FHIR-us-pacio-adi.xml, _updatePublisher.sh, input/fsh/ADIHeaderProfile.fsh, input/fsh/ADINotaryProfile.fsh, input/fsh/ADIWitnessProfile.fsh, input/fsh/ExamplesBetsySmith-Johnson.fsh, input/fsh/Extensions.fsh, input/fsh/PACPCompositionProfile.fsh
Please take a look and see if this looks correct - thanks!
=> Fhir 34512

input/pagecontent/security_privacy_consent.md
=> Applied resolution to security_privacy_consent under the Guidance menu

FHIR-us-pacio-adi.xml, input/fsh/ADIHeaderProfile.fsh, input/fsh/Aliases.fsh, input/fsh/DocumentReferenceProfile.fsh, input/fsh/Extensions.fsh, input/fsh/ValueSets.fsh
Created value set based on R5 Composition status value set and bound it to an extension in both ADI Composition and DocumentReference.
=> fix for FHIR46153 - document revoke status.

FHIR-us-pacio-adi.xml, input/fsh/CodeSystems_tbdcodes.fsh, sushi-config.yaml
ADI JIRA issue: FHIR-46312 - Add Temporary Code System.
=> added placeholder for Temporary Code System

input/pagecontent/content_type_overview.md
Also tightened up wording and highlighting in narrative to refer to FHIR resources.
=> Replaced STU1 scope with STU2 in narrative.

input/fsh/PACPCompositionProfile.fsh, input/fsh/PMOCompositionProfile.fsh
For FHIR-46312 (for PACP Comp) and FHIR-46475 (for PMO Comp)
=> constrained attester party

FHIR-us-pacio-adi.xml, input/fsh/CodeSystems_tbdcodes.fsh, input/fsh/PMOCompositionProfile.fsh, input/fsh/PMOServiceRequest.fsh
fixed intent = order and status = active for all PMO Order Service Requests.
=> added placeholder for medically assisted hydration order.

FHIR-us-pacio-adi.xml, input/fsh/ADIParticipantConsentProfile.fsh, input/fsh/Aliases.fsh, input/fsh/ValueSets.fsh
replaced ADI Consent Type scope to VSAC URL 2.16.840.1.113762.1.4.1115.13
=> fix for FHIR-40561

FHIR-us-pacio-adi.xml, input/fsh/PMOCompositionProfile.fsh, input/fsh/PMOProcedure.fsh, input/fsh/PMOServiceRequest.fsh
Also constrained ADI PMO ServiceRequest to require a start date value to indicate when the order goes into effect.
=> Fix for FHIR-46609 - constrain facilitator.

FHIR-us-pacio-adi.xml, input/fsh/ADIHeaderProfile.fsh, input/fsh/DocumentReferenceProfile.fsh, input/fsh/Example_PACP_BetsySmith-Johnson.fsh, input/fsh/Example_PACP_McBee.fsh, input/fsh/Example_PMO_BetsySmith-Johnson.fsh, input/fsh/Extensions.fsh, input/fsh/PMOCompositionProfile.fsh, input/fsh/PMOServiceRequest.fsh, input/fsh/ValueSets.fsh
created combined value set for Initial Treatment Options ServiceRequest.code.
=> fixed Composition and DocumentReference versionNumber.

input/fsh/ADIParticipantConsentProfile.fsh, input/fsh/Aliases.fsh, input/fsh/Example_PMO_BetsySmith-Johnson.fsh
per resolution description in [FHIR-40345](https://jira.hl7.org/browse/FHIR-40345), 
- changed cardinality of Consent.category to 1..1 
- fixed value to #acd.
=> fix for FHIR-40345

input/pagecontent/content_type1_pacp_user_stories.md
This could be a JIRA ticket number referenced here.
=> Fixed a type-o

input/pagecontent/index.md
Minor editorial changes for consistency and to update for changes we have already made in menu navigation labels, given the inclusion of MHAD specification under Person-Authored.
=> Update index.md - minor editorial changes and inclusion of MHAD

input/fsh/Example_PACP_BetsySmith-Johnson.fsh, input/fsh/Example_PACP_McBee.fsh, input/fsh/Example_PMO_BetsySmith-Johnson.fsh, input/fsh/PACPCompositionProfile.fsh, input/fsh/PMOCompositionProfile.fsh
Made attester a required field and updated examples.
=> Pre-applied fix for FHIR-46446 and FHIR-46475.

FHIR-us-pacio-adi.xml, input/fsh/ADICompositionHeaderProfile.fsh, input/fsh/Extensions.fsh
Also renamed FSH file from ADIHeaderProfile.fsh to ADICompositionHeaderProfile.fsh. This FSH filename change does not affect the model but it provides greater clarity for the IG author/profiler.
=> Fix for FHIR-48898.

input/fsh/PMOServiceRequest.fsh
Tightened constraint on ServiceRequest.intent in Profiles for entries in the Medical Orders Section by fixing ServiceRequest.intent = directive
=> Fix for FHIR-46671.

input/fsh/Aliases.fsh, input/fsh/ProvenanceProfile.fsh, sushi-config.yaml
also bound to agent:ProvenanceAuthor agent:ProvenanceTransmitter
=> bound Provenance.agent.role to L7DegreeLicenseCertificate.

input/fsh/Aliases.fsh
Changed Composition.extension.Jurisdiction to point to the US Core jurisdiction extension.
=> fix for FHIR-49201

input/fsh/Example_PMO_BetsySmith-Johnson.fsh, input/fsh/PMOCompositionProfile.fsh, input/pagecontent/StructureDefinition-ADI-PMOComposition-intro.md
Changed PMO Composition attester.mode from #professional to #legal.
=> Re-fixed FHIR-49808

FHIR-us-pacio-adi.xml, input/fsh/ADIHealthcareAgentConsentProfile.fsh, input/fsh/ADIJurisdictionProfile.fsh, input/fsh/ADIParticipantProfile.fsh, input/fsh/AL_Aliases.fsh, input/fsh/AutopsyObservationProfile.fsh, input/fsh/DocumentReferenceProfile.fsh, input/fsh/Example_PACP_BetsySmith-Johnson.fsh, input/fsh/Example_PMO_BetsySmith-Johnson.fsh, input/fsh/OrganDonationObservationProfile.fsh, input/fsh/SD_ADIFacilitator.fsh, input/fsh/ValueSets.fsh, input/ignoreWarnings.txt, input/pagecontent/content_type_overview.md, input/pagecontent/formal_specification.md, input/pagecontent/signatures.md
Also fixed more QAReport bugs.
=> Added Lisa edits to profile descriptions and narrative.
